final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fyp.urls', namespace='fyp')),
    path('', include('users.urls', namespace='users')),
]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('payment/', views.payment, name='payment-payment'),
    
    
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.fyp_login, name='fyp-login'),
    path('logout/', views.fyp_logout, name='fyp-logout'),
    path('register/', views.register, name='fyp-register'),
    path('profile/', views.profile, name='fyp-profile'),
    path('funds/', views.add_funds, name='fyp-add_funds'),
]

payment/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Payment(models.Model):
	title = models.CharField(max_length=100)
	amount = models.IntegerField()
	date_of_payment = models.DateTimeField(default=timezone.now)
	customer = models.ForeignKey(User, on_delete=models.CASCADE)


	def __str__(self):
		return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import User

class AppUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    funds = models.IntegerField(blank=True,null=True,default=0)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class LoginForm(forms.Form):
    username= forms.CharField(label="Username")
    password= forms.CharField(label='Password', widget=forms.PasswordInput)

fyp/views.py
from django.shortcuts import render


def welcome(request):
    return render(request, 'fyp/welcome.html')

payment/views.py
from django.shortcuts import render
from .models import Payment

# Create your views here.


def payment(request):
	context ={
		'payments' : Payment.objects.all()
	}
	return render(request, 'payment/payment.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from .forms import UserRegisterForm, LoginForm 
from .models import AppUser
# Create your views here.

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			login(request, user)
			messages.success(request, f'Account created for {username}! You are now able to log in')
			return redirect('fyp:fyp-welcome')
		else:
			messages.warning(request, f'Your password does not meet the criteria!')
	form = UserRegisterForm()
	return render(request, 'users/register.html', {'form': form})

def fyp_login(request):
	form = LoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, f'You are logged in as { username }')
			return redirect('fyp:fyp-welcome')
		else:
			messages.warning(request, f'The username or password is incorrect')
	else:
		return render(request, 'users/login.html', context={"form": form})

	form = LoginForm()
	return render(request, 'users/login.html', context={"form": form})

def fyp_logout(request):
	logout(request)
	return render(request, 'users/logout.html')
	return redirect('fyp:fyp-logout')
	


def profile(request):
	return render(request, 'users/profile.html')


def add_funds(request):
   
    return render(request, "users/add_funds.html")	

fyp/templates/fyp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   <link rel="stylesheet" type="text/css" href="{% static 'fyp/main.css' %}">


	{% if title %}
		<title>Customer Selfie Payment - {{ title }}</title>
	{% else %}
		<title>Customer Selfie Payment</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{% url 'fyp:fyp-welcome' %}"><b>Customer Selfie Payment</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                
                <a class="nav-item nav-link" href="{% url 'payment:payment-payment' %} ">Payment</a>
               
             
                <a class="nav-item nav-link" href="{% url 'users:fyp-profile' %} ">Profile</a>
              
               
                <a class="nav-item nav-link" href="{% url 'users:fyp-logout' %}">Logout</a>
                
            {% else %}
                
                <a class="nav-item nav-link" href="{% url 'users:fyp-login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'users:fyp-register' %}">Register</a>
                

            {% endif %}
        </div>

      </div>
    </div>
  </nav>
</header>

	<main role="main" class="container">

  <div class="row">
    <div class="col-md-8">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
      {% block content %} {% endblock %}
    </div>
  </div>
</main>
	
	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  

</body>
</html>

fyp/templates/fyp/welcome.html
{% extends "fyp/base.html" %}
{% block content %}

<style>
    #bg{
        background: url('fyp/static/fyp/pay.jpg') no-repeat;
        min-height: 980px;
        background-size: cover;
        background-attachment: fixed;
        overflow: hidden;
    }
</style>
<body id="bg">
    <div class="container">
        <h1 class="title text-center">
            <strong>Get Started As A Freelancer <br>Or<br> Get Your Things Done</strong>
        </h1>
        {% if not user.is_authenticated %}
        <div class="text-center mt-4">
            <a href="{% url 'users:fyp-login' %}"><button class="btn btn-primary btn-large" style="margin-right: 50px;">Login</button></a>
            <a href="{% url 'users:fyp-register' %}"><button class="btn btn-success btn-large">Register</button></a>
        </div>
        {% else %}
        <div class="text-center mt-4">
            <a href="{% url 'payment:payment-payment' %}"><button class="btn btn-primary btn-large" style="margin-right: 50px;">Payment</button></a>
            <a href="{% url 'users:fyp-profile' user.id %}"><button class="btn btn-success btn-large">Profile</button></a>
        </div>
        {% endif %}
    </div>
</body>
{% endblock content %}

payment/templates/payment/payment..html
{% extends "fyp/base.html" %}
{% block content %}
	{% for payment in payments %}
		<article class="media content-section">
  			<div class="media-body">
    		<div class="article-metadata">
     	 <a class="mr-2" href="#">{{ payment.customer }}</a>
      <small class="text-muted">{{ payment.date_of_payment|date:"F d, Y" }}</small>
    </div>
    	<h2><a class="article-title" href="#">{{ payment.title }}</a></h2>
   	 <p class="article-content">{{ payment.amount }}</p>
  		</div>
		</article>
	{% endfor %}
	{% endblock content %}

users/templates/users/add_funds.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <input type="text"  name="fund" placeholder="Enter Amount">
    <button type="submit" class=" btn btn-primary">Add Amount </button>
</form>
{% endblock content %}

users/templates/users/login.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"><b>Log In</b></legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Log In</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Don't Have An Account?<a class="ml-2" href="{% url 'users:fyp-register' %}">Sign Up</small>
		</div>
	</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "fyp/base.html" %}
{% block content %}
		<h2>You have been logged out!</h2>
		<div class="border-top pt-3">
			<small class="text-muted"><a href="{% url 'users:fyp-login' %}">Log In Again</small>
		</div>
	</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
	{% block title %}
		View Profile
	{% endblock %}

{% block content %}
<h1 class="text-center">Profile</h1>

<hr>
<div class="row mb-5">
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <img src="https://www.windstream.com/getmedia/b2e4e38a-7cb6-4ca9-9544-54dfeaca6304/icon_user-circle.png.aspx?width=1520&height=980&ext=.png"
                class="card-img-top" alt="img">
            <div class="card-body" style="margin-bottom: -20px;">
                
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Username: {{ user.username }}</li>
                <li class="list-group-item">Email: {{ user.email }}</li>
                
                
                <li class="list-group-item"> Balance :</li>
                <li class="list-group-item"><a href="{% url 'users:fyp-add_funds' %}"><button class="btn btn-primary btn-sm">Add Funds</button></a>
                <a href="#"><button class="btn btn-primary btn-sm">View Payment</button></a></li>
               
               
                    
                
            </ul>
	 	</div>
	</div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "fyp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"><b>Sign Up </b> </legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Sign Up</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Already Have An Account?<a class="ml-2" href="{% url 'users:fyp-login' %}">Log In</small>
		</div>
	</div>
{% endblock content %}